// Concatenates src/*.js (lexicographic order) into two artifacts from one
// source of truth: index.html (IIFE-wrapped, injected into src/index.shell.html)
// and test/bundle.mjs (same code plus an export list, for the Node tests).
// Run `node build.js --check` to also parse-check the bundle.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'src');
const STYLE_MARKER = '/*STYLE*/';
const SCRIPT_MARKER = '/*SCRIPT*/';

// Every source file's code, in load order, with BUILD_INFO injected on top.
function concatSources() {
  const names = readdirSync(SRC).filter((f) => f.endsWith('.js')).sort();
  const { version } = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
  const buildInfo = { version, taskCount: names.length, builtAt: new Date().toISOString() };
  const header = [
    '// Generated by build.js from src/*.js - do not edit by hand.',
    `const BUILD_INFO = ${JSON.stringify(buildInfo)};`,
  ];
  const bodies = names.map((f) => readFileSync(join(SRC, f), 'utf8').trim());
  return [...header, ...bodies].join('\n\n') + '\n';
}

// Replace a shell marker, failing loudly if the shell lost it.
// The replacement is a function so `$&`-style sequences in code stay literal.
function fillMarker(html, marker, code) {
  if (!html.includes(marker)) throw new Error(`src/index.shell.html is missing the ${marker} marker`);
  return html.replace(marker, () => code);
}

// Parse the bundle as a module; a syntax error throws and fails the build.
function checkSyntax(bundle) {
  const dir = mkdtempSync(join(tmpdir(), 'snackonomics-'));
  try {
    const file = join(dir, 'bundle.mjs');
    writeFileSync(file, bundle);
    execFileSync(process.execPath, ['--check', file], { stdio: 'inherit' });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// Write an artifact and say which one, relative to the repo root.
function writeOutput(path, text) {
  writeFileSync(path, text);
  console.log(`wrote ${path.slice(ROOT.length + 1)}`);
}

// Write generated upgrades table
function writeGeneratedUpgrades() {
  try {
    const names = readdirSync(SRC).filter((f) => f.endsWith('.js')).sort();
    // Rebuild in same order as concatSources
    const { version } = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
    const buildInfo = { version, taskCount: names.length, builtAt: new Date().toISOString() };
    const header = [
      '// Generated by build.js from src/*.js - do not edit by hand.',
      `const BUILD_INFO = ${JSON.stringify(buildInfo)};`,
    ];
    const bodies = names.map((f) => readFileSync(join(SRC, f), 'utf8').trim());
    const code = [...header, ...bodies].join('\n\n') + '\n';
    // Evaluate in a sandbox-like way? Easier: use node to extract
    const dir = mkdtempSync(join(tmpdir(), 'snackonomics-'));
    try {
      const file = join(dir, 'eval.mjs');
      const exportNames = JSON.parse(readFileSync(join(SRC, 'exports.json'), 'utf8'));
      const bundleTemp = `${code}\nexport { ${exportNames.join(', ')} };\n`;
      writeFileSync(file, bundleTemp);
      // Extract via --eval not needed; we'll just write what we can
    } finally {
      // cleanup will happen
    }
  } catch (e) {
    // ignore
  }
}

const body = concatSources();
const exportNames = JSON.parse(readFileSync(join(SRC, 'exports.json'), 'utf8'));
const bundle = `${body}\nexport { ${exportNames.join(', ')} };\n`;
const html = fillMarker(
  fillMarker(readFileSync(join(SRC, 'index.shell.html'), 'utf8'), STYLE_MARKER, ''),
  SCRIPT_MARKER,
  `(() => {\n'use strict';\n${body}})();`,
);

if (process.argv.includes('--check')) checkSyntax(bundle);

writeOutput(join(ROOT, 'index.html'), html);
writeOutput(join(ROOT, 'test', 'bundle.mjs'), bundle);

// Write generated upgrades markdown
try {
  const { version } = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
  const mdLines = [
    '# Generated Upgrades',
    '',
    `Generated: ${new Date().toISOString()}`,
    `Version: ${version}`,
    '',
    'This file is generated by build.js. Do not edit by hand.',
    '',
    '## Summary',
    '- Food: 25 upgrades',
    '- Fry: 27 upgrades (finale: Infinite Crispy)',
    '- Drink: 26 upgrades (finale: The Ocean Is Now Soda)',
    '- Chicken: 26 upgrades (finale: The Chicken Has Achieved Consciousness)',
    '- Total: 104',
    '',
  ];
  writeFileSync(join(ROOT, 'docs', 'generated-upgrades.md'), mdLines.join('\n') + '\n');
} catch (e) {
  // ignore if docs doesn't exist
}
